'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmApproval

    '''<summary>
    '''UpdatePanelCourseMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCourseMaster As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbl_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddl_Mode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Mode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TabContainer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer2 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''TbApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbApproval As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddl_Semester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Semester As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_ExpiredOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ExpiredOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Expired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Expired As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Expired_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Expired_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lbl_AppFaculty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AppFaculty As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''txt_FacultyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FacultyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_FacultyID_AutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FacultyID_AutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_FacultyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FacultyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_FacultyName_Extender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FacultyName_Extender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblStudentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_StudentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_StudentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ACE_Stud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ACE_Stud As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''ddl_StudName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_StudName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_CSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CSID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_CourseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CourseID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ace_CourseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ace_CourseID As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''ddlCourseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCourseName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_PreReqCSD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PreReqCSD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PreReqCSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PreReqCSID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ace_PreReqCSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ace_PreReqCSID As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''ddl_PreReqCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_PreReqCSName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAssignmentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignmentID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_AssignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AssignID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ace_AssID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ace_AssID As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''ddlAssName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAssName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Comments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_RegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RegDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_AttachDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AttachDoc As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''FileUploaDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploaDoc As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btn_UploadDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_UploadDoc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_ViewAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ViewAttachments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbSearch As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Panel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_SFaculty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_SFaculty As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''txt_SFacultyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SFacultyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SFacultyID_Extender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SFacultyID_Extender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_SFacultyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SFacultyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SFacultyName_Extender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SFacultyName_Extender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_SStudentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SStudentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SStudentID_Extender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SStudentID_Extender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_SStudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SStudentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SStudentName_Extender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SStudentName_Extender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''lbl_Semester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Semester As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_SMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SMID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ace_SMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ace_SMID As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_SMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SMName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ace_SMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ace_SMName As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''btn_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_ClearS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ClearS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelCourseMaster0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCourseMaster0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gdv_ApprovalSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_ApprovalSettings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Print As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Hdn_Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hdn_Grid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_index control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_index As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_Control control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_Control As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_TeachersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_TeachersName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_SemsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_SemsName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_exportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_exportExcel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_ViewAttchDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_ViewAttchDoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ModalPopupExtenderViewAttachDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderViewAttachDoc As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''DivViewAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivViewAttach As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnl_ViewAttchdDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_ViewAttchdDoc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gdv_ViewAttachdDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_ViewAttachdDoc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_CloseRegStud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CloseRegStud As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_Find control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_Find As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_DocID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_DocID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btn_Confirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Confirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Hdn_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hdn_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ValidationSummaryCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryCourse As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''hdn_Mode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_Mode As Global.System.Web.UI.WebControls.HiddenField
End Class
